### ISSUE TITLE
Support Persistent Volume and Persistent Volume Claim in Model

### ISSUE THREAD

**Issue by sherl0cks** [rht-labs/api-design#35]
See https://github.com/rht-labs/ansible-stacks/issues/30

Cluster should have volumes
Project should have claim
App should use the claim name

**Comment by oybed** [comment]
for PV, need the following parameters:

```
metadata:
  name: <name>
spec:
  capacity:
    storage: <size> Gi
  accessModes:
  - <mode>
  nfs: 
    path: <nfs_server_export_path>
    server: <nfs_server_fqdn_or_ip>
  persistentVolumeReclaimPolicy: <policy>
```

**Comment by oybed** [comment]
For PVC, need the following parameters:

```
metadata:
  name: <name>
spec:
  accessModes:
    - <mode>
  resources:
    requests:
      storage: <size>Gi  
```
